services:
  initdb:
    image: ${DOCKER_REGISTRY-}initdb
    build:
      context: .
      dockerfile: Initdb/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=db;Initial Catalog=GenePrioritizer;User ID=sa;Password=YourStrong!Passw0rd;Encrypt=False;Max Pool Size=32767"
    volumes:
      - .:/src
    depends_on:
      - db

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Webapi/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=db;Initial Catalog=GenePrioritizer;User ID=sa;Password=YourStrong!Passw0rd;Encrypt=False;Max Pool Size=32767"
    depends_on:
      - db
    ports:
      - "80:8080"
  db:
    image: ${DOCKER_REGISTRY-}db
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

      # initdb
      - .:/src

volumes:
  sqlserver_data: